#!/bin/bash
# Run a SAM test

set -e

name=$1
basename=$(basename $name)

graphics_log=""
if [[ "${basename#screen_}" != "$basename" ]]; then
    graphics_log="--dump-screen $basename-output.pbm"
fi

go run $top_srcdir --debug $graphics_log "$name" > "$basename-output.log" 2>&1
sed -e 's/sam_run: pc0 = [0-9a-fx]\+/sam_run: pc0 = XXXXXXXX/g' -e 's/, ir = [0-9a-fx]\+/, ir = XXXXXXXX/g' -e 's/- ref [0-9a-fx]\+/- ref XXXXXXXX/g' -e 's/- stack [0-9a-fx]\+/- stack XXXXXXXX/g' -e 's/^Stack: [0-9a-fx]\+/Stack: XXXXXXXX/g' < "$basename-output.log" > "$basename-fixed.log"
diff -u "$name-expected.log" "$basename-fixed.log"
if [[ "$graphics_log" != "" ]]; then
    diff -u "$name-expected.pbm" "$basename-output.pbm"
fi
