#!/bin/bash
# Run a SAM test

set -e

test_file=$1
name=${1%.yaml}
basename=$(basename $name)

graphics_log=""
if [[ "${basename#screen_}" != "$basename" ]]; then
    graphics_log="--dump-screen $basename-output.pbm"
fi

go run . --debug $graphics_log "$test_file" > "$basename-output.log" 2>&1
diff -u "$srcdir/$basename-expected.log" "$basename-output.log"
if [[ "$graphics_log" != "" ]]; then
    diff -u "$srcdir/$basename-expected.pbm" "$basename-output.pbm"
fi
