// Sam graphics traps.
//
// (c) Reuben Thomas 2020-2025
//
// The package is distributed under the GNU Public License version 3, or,
// at your option, any later version.
//
// THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
// RISK.

#ifndef SAM_TRAP_GRAPHICS
#define SAM_TRAP_GRAPHICS

#include "sam.h"

sam_word_t sam_graphics_trap(sam_state_t *state, sam_uword_t function);
char *sam_graphics_trap_name(sam_word_t function);

#define SAM_TRAP_GRAPHICS_BASE 0x200

enum SAM_TRAP_GRAPHICS {
  // Graphics
  // Origin 0,0 is at top left.
  TRAP_GRAPHICS_BLACK = SAM_TRAP_GRAPHICS_BASE,
  TRAP_GRAPHICS_WHITE,
  TRAP_GRAPHICS_DISPLAY_WIDTH,
  TRAP_GRAPHICS_DISPLAY_HEIGHT,
  TRAP_GRAPHICS_CLEARSCREEN,
  TRAP_GRAPHICS_SETDOT,
  TRAP_GRAPHICS_DRAWLINE,
  TRAP_GRAPHICS_DRAWRECT,
  TRAP_GRAPHICS_DRAWROUNDRECT,
  TRAP_GRAPHICS_FILLRECT,
  TRAP_GRAPHICS_DRAWCIRCLE,
  TRAP_GRAPHICS_FILLCIRCLE,
  TRAP_GRAPHICS_DRAWBITMAP,
  TRAP_GRAPHICS_TEXT,
  TRAP_GRAPHICS_FONT_MONO,
  TRAP_GRAPHICS_FONT_MONO_BOLD,
  TRAP_GRAPHICS_FONT_REGULAR,
  TRAP_GRAPHICS_FONT_ITALIC,
  TRAP_GRAPHICS_FONT_BOLD,
  TRAP_GRAPHICS_FONT_BOLDITALIC,
  TRAP_GRAPHICS_FONT_EMOJI,
  TRAP_GRAPHICS_FPS,
  TRAP_GRAPHICS_WAIT,
};

#endif
