// Sam graphics traps.
//
// (c) Reuben Thomas 2020-2025
//
// The package is distributed under the GNU Public License version 3, or,
// at your option, any later version.
//
// THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
// RISK.

#ifndef SAM_TRAP_GRAPHICS
#define SAM_TRAP_GRAPHICS

#include "sam.h"

sam_word_t sam_graphics_trap(sam_state_t *state, sam_uword_t function);
char *sam_graphics_trap_name(sam_word_t function);

#define SAM_TRAP_GRAPHICS_BASE 0x200

enum SAM_TRAP_GRAPHICS {
    // Graphics
    // Origin 0,0 is at top left.

    // Colours
    TRAP_GRAPHICS_BLACK = SAM_TRAP_GRAPHICS_BASE,
    TRAP_GRAPHICS_WHITE,
    TRAP_GRAPHICS_RED,
    TRAP_GRAPHICS_GREEN,
    TRAP_GRAPHICS_LIME = TRAP_GRAPHICS_GREEN,
    TRAP_GRAPHICS_BLUE,
    TRAP_GRAPHICS_CYAN,
    TRAP_GRAPHICS_MAGENTA,
    TRAP_GRAPHICS_FUSCHIA = TRAP_GRAPHICS_MAGENTA,
    TRAP_GRAPHICS_YELLOW,
    TRAP_GRAPHICS_SILVER,
    TRAP_GRAPHICS_GRAY,
    TRAP_GRAPHICS_GREY = TRAP_GRAPHICS_GRAY,
    TRAP_GRAPHICS_CHARCOAL,
    TRAP_GRAPHICS_SPRING_GREEN,
    TRAP_GRAPHICS_VIOLET,
    TRAP_GRAPHICS_SKY_BLUE,
    TRAP_GRAPHICS_ORANGE,
    TRAP_GRAPHICS_BLUE_GREEN,
    TRAP_GRAPHICS_PINK,
    TRAP_GRAPHICS_FADED_BLUE,
    TRAP_GRAPHICS_FADED_GREEN,
    TRAP_GRAPHICS_FADED_CYAN,
    TRAP_GRAPHICS_FADED_RED,
    TRAP_GRAPHICS_BRICK_RED = TRAP_GRAPHICS_FADED_RED,
    TRAP_GRAPHICS_FADED_PINK,
    TRAP_GRAPHICS_FADED_YELLOW,
    TRAP_GRAPHICS_DARK_RED,
    TRAP_GRAPHICS_MAROON = TRAP_GRAPHICS_DARK_RED,
    TRAP_GRAPHICS_DARK_GREEN,
    TRAP_GRAPHICS_NAVY,
    TRAP_GRAPHICS_PURPLE,
    TRAP_GRAPHICS_OLIVE,
    TRAP_GRAPHICS_TEAL,
    TRAP_GRAPHICS_LIGHT_SKY_BLUE,
    TRAP_GRAPHICS_BROWN,
    TRAP_GRAPHICS_GOLD,
    TRAP_GRAPHICS_BRONZE,
    TRAP_GRAPHICS_FAIR_SKIN,
    TRAP_GRAPHICS_WHITE_SKIN = TRAP_GRAPHICS_FAIR_SKIN,
    TRAP_GRAPHICS_MEDIUM_SKIN,
    TRAP_GRAPHICS_OLIVE_SKIN = TRAP_GRAPHICS_MEDIUM_SKIN,
    TRAP_GRAPHICS_LIGHT_BROWN_SKIN,
    TRAP_GRAPHICS_BROWN_SKIN,
    TRAP_GRAPHICS_BLACK_SKIN,
    TRAP_GRAPHICS_DARK_BROWN_SKIN = TRAP_GRAPHICS_BLACK_SKIN,

    TRAP_GRAPHICS_DISPLAY_WIDTH,
    TRAP_GRAPHICS_DISPLAY_HEIGHT,
    TRAP_GRAPHICS_CLEARSCREEN,
    TRAP_GRAPHICS_SETDOT,
    TRAP_GRAPHICS_DRAWLINE,
    TRAP_GRAPHICS_DRAWRECT,
    TRAP_GRAPHICS_DRAWROUNDRECT,
    TRAP_GRAPHICS_FILLRECT,
    TRAP_GRAPHICS_DRAWCIRCLE,
    TRAP_GRAPHICS_FILLCIRCLE,
    TRAP_GRAPHICS_DRAWBITMAP,
    TRAP_GRAPHICS_TEXT_SIZE,
    TRAP_GRAPHICS_TEXT,
    TRAP_GRAPHICS_TEXTBOX,
    TRAP_GRAPHICS_FONT_MONO,
    TRAP_GRAPHICS_FONT_MONO_BOLD,
    TRAP_GRAPHICS_FONT_REGULAR,
    TRAP_GRAPHICS_FONT_ITALIC,
    TRAP_GRAPHICS_FONT_BOLD,
    TRAP_GRAPHICS_FONT_BOLDITALIC,
    TRAP_GRAPHICS_FONT_EMOJI,
    TRAP_GRAPHICS_FPS,
    TRAP_GRAPHICS_WAIT,
};

#endif
