#!/bin/sh

if test $# -lt 1; then
    echo Usage: mksam PROGRAM.YAML
    exit 1
fi

./samc < $1 > sam_program.h
wc -l < sam_program.h > sam_program_len.h
gcc -W -m32 -g -DSAM_DEBUG -o sam sam_*.c -x c sam_main.x -x c sam_traps.x -lSDL2 -lSDL2_gfx
