#!/bin/bash
# Run a SAM test

set -e

test_file=$1
name=${1%.yaml}
basename=$(basename $name)
sam_exe=test-$basename

./mksam "$test_file" $sam_exe
./$sam_exe > "$basename-output.log" 2>&1
diff -u "$srcdir/$basename-expected.log" "$basename-output.log"
