(SAM_INSN_PUSH << SAM_OP_SHIFT) | SAM_OP_INSN,
  0x41a80000, // 21.0F,
  (SAM_INSN_PUSH << SAM_OP_SHIFT) | SAM_OP_INSN,
  0x40000000, // 2.0F,
  (SAM_INSN_MUL << SAM_OP_SHIFT) | SAM_OP_INSN,
  (SAM_INSN_PUSH << SAM_OP_SHIFT) | SAM_OP_INSN,
  0x40400000, // 3.0F
  (SAM_INSN_NEG << SAM_OP_SHIFT) | SAM_OP_INSN,
  SAM_OP_LIT, // 0
  (SAM_INSN_DUP << SAM_OP_SHIFT) | SAM_OP_INSN,
  (1 << SAM_OP_SHIFT) | SAM_OP_LIT, // 1
  (SAM_INSN_SWAP << SAM_OP_SHIFT) | SAM_OP_INSN,
  (SAM_INSN_ADD << SAM_OP_SHIFT) | SAM_OP_INSN,
  SAM_OP_LIT, // 0
  (SAM_INSN_SWAP << SAM_OP_SHIFT) | SAM_OP_INSN,
  (SAM_INSN_DIV << SAM_OP_SHIFT) | SAM_OP_INSN,
  (SAM_INSN_THROW << SAM_OP_SHIFT) | SAM_OP_INSN,
