name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-15
      ASAN_FLAGS: "-fsanitize=address -fsanitize=undefined"
      CGO_CFLAGS_ALLOW: -fno-strict-overflow

    steps:
      - uses: actions/checkout@v6
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install dependencies
        run: |
          brew install coreutils automake pkg-config go sdl2_mixer libgrapheme gcc
          # Prepend optional brew binary directories to PATH
          echo "$(brew --prefix m4)/bin:$(brew --prefix binutils)/bin:${PATH}" >> $GITHUB_PATH
      - name: configure
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix systemd)/lib/pkgconfig:$PKG_CONFIG_PATH"
          autoreconf -fi && ./configure && go mod download
      - name: make
        run: make --jobs=`nproc`
        env:
          CFLAGS: -g ${{ env.ASAN_FLAGS }}
          CXXFLAGS: -g ${{ env.ASAN_FLAGS }}
          LDFLAGS: ${{ env.ASAN_FLAGS }}
      - name: make check
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix systemd)/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH=$(brew --prefix)/lib
          go run . --debug test/iter.sal # Useful for debug
          make check --jobs=`nproc` || ( cat test/test-suite.log && exit 1 )
      - name: make distcheck
        # normal build is with ASAN, distcheck is without ASAN. Both are covered.
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix systemd)/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH=$(brew --prefix)/lib
          make distcheck --jobs=`nproc` || ( cat sam-*/_build/sub/test/test-suite.log && exit 1 )

  # build-windows:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   strategy:
  #     matrix:
  #       include:
  #       - { sys: mingw64, env: x86_64 }
  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       release: false
  #       msystem: ${{matrix.sys}}
  #       install: >-
  #         patch git groff
  #         mingw-w64-${{matrix.env}}-autotools
  #         mingw-w64-${{matrix.env}}-pkg-config
  #         mingw-w64-${{matrix.env}}-gcc
  #         mingw-w64-${{matrix.env}}-go
  #         mingw-w64-${{matrix.env}}-SDL2_mixer
  #   - uses: actions/checkout@v6
  #   - name: configure
  #     run: autoreconf -fi && ./configure && go mod download
  #   - name: make
  #     run: make --jobs=`nproc`
  #   - name: make check
  #     run: make check --jobs=`nproc` || ( cat test-suite.log && exit 1 )
  #   - name: make distcheck
  #     run: make distcheck --jobs=`nproc` || ( cat sam-*/_build/sub/test-suite.log && exit 1 )
